LatestPetsApp/PetsApplication/PetsApplication/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PetsApplication;
using PetsApplication.Models;
using Microsoft.AspNet.Identity;
using System.Web.Security;
using PetsApplication.Controllers;

namespace PetsApplication.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        private CustomerDbContext context = new CustomerDbContext();
        public ActionResult Home()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Details()
        {
            string cookieName = FormsAuthentication.FormsCookieName; //Find cookie name
            HttpCookie authCookie = HttpContext.Request.Cookies[cookieName]; //Get the cookie by it's name
            FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(authCookie.Value); //Decrypt it
            string UserName = ticket.Name;

            using (CustomerDbContext context = new CustomerDbContext())
            {
                int UserID = context.Registers.Where(x => x.name == UserName).Select(x => x.id).FirstOrDefault();

                string name = HttpContext.Profile.UserName;
                var data = context.Registers.Where(x => x.id == UserID).ToList();

                return View(data);
            }
        }

        public int Current_UserID()
        {
            CustomerDbContext context = new CustomerDbContext();
            int UserId = 0;
            string cookieName = FormsAuthentication.FormsCookieName; //Find cookie name
            HttpCookie authCookie = HttpContext.Request.Cookies[cookieName]; //Get the cookie by it's name
            FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(authCookie.Value); //Decrypt it
            string UserName = ticket.Name;
            UserId = context.Registers.Where(x => x.name == UserName).Select(x => x.id).FirstOrDefault();
            return UserId;
        }

        public ActionResult Edit(int id)
        {

            using (CustomerDbContext context = new CustomerDbContext())
            {
                Register r = context.Registers.Find(id);
                if (r == null)
                {
                    return HttpNotFound();
                }
                return View(r);

            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Exclude = "name")]Register register)
        {
            Register registerFromDb = context.Registers.Single(x => x.id == register.id);
            registerFromDb.city = register.city;
            registerFromDb.email = register.email;
            registerFromDb.password = register.password;
            register.name = registerFromDb.name;
            if (ModelState.IsValid)
            {
                context.Entry(registerFromDb).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Details");


            }
            return View(register);
        }


    }
}

LatestPetsApp/PetsApplication/PetsApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Pets</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<img src="~/images/logo_pet.png" alt="Sample Photo" />*@
                @Html.ActionLink("Online Pets", "Home", "Customer", new { area = "" }, new { @class = "navbar-brand" })
            </div>
           
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Home", "Customer")</li>
                    <li>@Html.ActionLink("Pets", "index", "Products")</li>
                    <li>@Html.ActionLink("Orders", "OrderDetails", "Products")</li>
                    <li>@Html.ActionLink("CustomerDetails", "Details", "Customer")</li>
                    @*@Html.ActionLink("Cart", "CustomerOrders", "Products", new { @class = "btn-sm glyphicon glyphicon-shopping-cart navbar-left" })*@
                </ul>
                @Html.Partial("_LoginPartial")
              
            </div>
            <li>
                

            @*<span class="glyphicon glyphicon-shopping-cart"></span>*@ 
        </li>
            
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -Pets Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

LatestPetsApp/PetsApplication/PetsApplication/Views/Shared/_SuccesView.cshtml
<div>
   You Have Sucessfully Added To The Cart !!
</div>